name: MyXmonad
version: 0.1.0
synopsis: xmonad setting
dependencies:
  - X11
  - base
  - xmonad
  - xmonad-contrib
  - containers
executables:
  xmonad:
    main: xmonad.hs
    ghc-options:
      - -Wall
      - -fwarn-tabs
      - -threaded
      - -O2
      - -with-rtsopts=-N4
